const g = [
   'Gage',
   'Ganove',
   'Geäst',
   'Gebälk',
   'gediegen',
   'Gehabe',
   'geheftet',
   'geizen',
   'Gekrächz',
   'Gelände',
   'Geländer',
   'gelinde',
   'Gemurmel',
   'gepfeffert',
   'Geplänkel',
   'Geplapper',
   'gerädert (sich wie g. fühlen)',
   'Geräuschkulisse',
   'gerieren',
   'gerinnen',
   'Gerippe',
   'gerissen',
   'Gerümpel',
   'Gerüst',
   'gesalzen',
   'geschliffen',
   'geschniegelt',
   'Geschwafel',
   'Gesindel',
   'gesittet',
   'Gestänge',
   'Gestell',
   'Gestöber',
   'getäfelt, täfeln',
   'Getümmel',
   'Geturtel',
   'Gewebe',
   'Gewese',
   'Gewimmel',
   'Gewirr',
   'Gewühl',
   'gewunden',
   'Gier',
   'giften',
   'giggeln',
   'Gips',
   'glimpflich',
   'glotzen',
   'gluckern',
   'Gör, Göre',
   'Gosse',
   'grapschen',
   'große Stücke auf jdn. halten',
   'Grünschnabel',
   'grunzen',
   'Grüßaugust',
   'gurren',
   'Gurt',       
   'gut in Schuss',       
 ];

export default g;