const g = [
   'Ganove',
   'Gebälk',
   'gediegen',
   'Gehabe',
   'geheftet',
   'geizen',
   'Gekrächz',
   'Gelände',
   'Geländer',
   'gelinde',
   'Gemurmel',
   'gepfeffert',
   'Geplänkel',
   'Geplapper',
   'gerinnen',
   'Gerippe',
   'gerissen',
   'Gerümpel',
   'Gerüst',
   'gesalzen',
   'geschliffen',
   'geschniegelt',
   'Geschwafel',
   'Gesindel',
   'Gestänge',
   'Gestell',
   'Gestöber',
   'Getümmel',
   'Geturtel',
   'Gewebe',
   'Gewese',
   'Gewimmel',
   'Gewühl',
   'gewunden',
   'Gier',
   'giften',
   'giggeln',
   'glimpflich',
   'glotzen',
   'gluckern',
   'Gör, Göre',
   'Gosse',
   'grapschen',
   'Grünschnabel',
   'grunzen',
   'gurren',
   'Gurt',       
   'gut in Schuss',       
 ];

export default g;