const h = [
   'Häkchen',  
   'haken, Haken',
   'Halunke',
   'Handwerk legen',
   'hanebüchen',
   'hart im Nehmen sein',
   'Hautausschlag' ,
   'hecheln',  
   'hechten, Hechtsprung',
   'Heckenschütze',
   'Heft des Handelns nehmen',
   'Heidenrespekt/angst',
   'Heimtücke, heimtückisch',
   'heimzahlen',
   'heiser',
   'hereinlegen',
   'herumlungern',
   'hetzen',
   'heulen',
   'hocken, Hocke',
   'Hölle heißmachen',
   'Hornochse',
   'Hosenmatz',
   'Hosennaht',
   'Hühnerauge',
   'humpeln',
   'huschen',
 ];

export default h;