const h = [
   'Häkchen',  
   'haken, Haken, Haken schlagen',
   'halbseiden',
   'Halunke',
   'hämisch',
  // 'hämmern',
   'Handfessel, Handschelle',
   'Handwerk legen',
   'hanebüchen',
   'hapern',
   'harren',
   'hart im Nehmen sein',
   'Hatz',
   'hausieren',
   'Hautausschlag' ,
   'hecheln',  
   'hechten, Hechtsprung',
   'Heckenschütze',
   'Heft des Handelns nehmen',
   'Heidenrespekt/angst',
   'Heimtücke, heimtückisch',
   'heimzahlen',
   'heiser',
   'Hemd (sich ins H. machen)',
   'hereinlegen',
   'herumlungern',
   'hetzen',
   'heucheln',
   'heulen',
   'hinterlistig',
   'hinters Licht führen',
   'hocken, Hocke, Hocker',
   'Hölle heißmachen',
   'Holzstoß',
   'hopsnehmen',
   'Hornochse',
   'Hose (in die Hosen machen)',
   'Hosenmatz',
   'Hosennaht',
   'Hühnerauge',
   'humpeln',
   'huschen',
 ];

export default h;