const k = [
   'kahl',
   'kämmen',
   'Karree',
   'karren',
   'Kaschemme',
   'kaschieren',
   'Kassiber',
   'katzbuckeln',
   'kauern',
   'kauzig',
   'keinen Reim machen können',
   'Kelch',
   'ketten, Kette',
   'kichern',
   'Kieker (auf dem Kieker haben)',
   'Kiesweg',   
   'Kinderficker',
   'Kittel',  
   'kitzeln', 
   'klackern',
   'Kladde',
   'klamm',
   'Klammer',
   'klammern',
   'klappern',  
   'klapprig',
   'Klapsmühle',
   'klatschen',
   'klauben',
   'Klaue',
   'Klemme',
   'klemmen',
   'Klette',
   'klimpern',
   'Klinge',
   'klirren',
   'klitzeklein',
   'Kloß',
   'Klumpen, Klumpfuß',
   'Klüngel',
   'knallen', 
   'Knarre',
   'knarren',
   'Knäuel',
   'kneten',
   'knebeln', 
   'kneifen',
   'kneten', 
   'Knirps',
   'knirschen',  
   'knistern', 
   'Knöchel',  
   'Knochen hinhalten', 
   'knuffen',
   'Knüller',
   'Knüppel',
   'knurren',
   'Köder',
  // 'Kontor',
   'Konterfei',
   'köpfen',
   'Korb (einen Korb bekommen)',
   'Kordel',
   'Kot, Kotflügel',
   'koten',
   'krabbeln',  
   'krachen', 
   'Krähe, krähen',  
   'krakelig/kraklig',
   'Kram (jmdm. in den Kram passen)',
   'kramen',
   'Kran',
   'Kratzbürstigkeit',
   'kraulen',
   'Kreisel',
   'Krempe',
   'Krempel',
   'Kribbeln',
   'kritzeln' ,
   'krümmen (sich)',
   'kullern',
   'Kuppel',
   'kurbeln',
   'kuscheln (sich)',
   'kuschen',
];

export default k;   