const l = [
   'Lack',
   'lädieren',
   'laff',
   'Laken',
   'lallen',
   'lässig',
   'Laufbursche',
   'Leier',   
   'leiern',   
   'Leim, leimen',   
   'Leinen',   
   'Leiste',  
   'lichterloh brennen',
   'Litfaßsäule',
   'Loch in den Bauch fragen',
   'lodern',
   'loseisen',
   'Luder',
   'lugen',             
   'lumpen lassen (sich nicht)',
   'Lunte riechen',
];

export default l;      