const p = [
   'Pächter',
   'paktieren',
   'Pantoffel (unter dem P. stehen)',
   'Pappe',
   'Pappenstiel',
   'Pegel',
   'Pest an den Hals',
   'petzen',
   'Pfaffe',
   'Pfanne (in die P. hauen)',
   'Pfau'  ,
   'pfeffern',
   'Pfeiler',
   'pferchen, einpferchen',
   'pfiffig',
   'Pfropfen',
   'pfuschen (ins Handwerk p.)', //review this, make conincide with "ins Handwerk pfuschen" under "i"
   'Pfütze',    
   'pieksen, piksen',
   'Pinkel' ,
   'pinkeln' ,
   'pinseln' ,  // pinseln:
   'Plackerei',
   'platschen',
   'Platzhirsch',
   'ploppen' ,
   'plumpsen',
   'plüschig',  // plüschig:
   'Polster, polstern', //
   'poltern' ,
   'postieren',
  // 'präparieren' ,
   'Pranke',
   'Präsent, präsent',
   'prasseln',
   'Prise' ,
   'Pritsche',
   'Prothese',
   'Protz, protzen, protzig' ,
   'prusten',
   'pudern',
   'Pulle',
   'Pute',
  ];

export default p;      