const p = [
   'paktieren',
   'Pantoffel (unter dem P. stehen)',
   'Pappe',
   'Pappenstiel',
   'petzen',
   'Pfaffe',
   'Pfanne (in die Pfanne hauen)',
   'Pfau'  ,
   'pfeffern',
   'Pfeiler',
   'pferchen',
   'pfiffig',
   'pfuschen (ins Handwerk pfuschen)',
   'pieksen, piksen',
   'Pinkel' ,
   'pinkeln' ,
   'pinseln' ,
   'platschen',
   'Platzhirsch',
   'ploppen' ,
   'plumpsen',
   'plüschig',
   'Polster',
   'poltern' ,
   'postieren',
  // 'präparieren' ,
   'Pranke',
   'Prise' ,
   'Pritsche',
   'Protz' ,
   'Pulle',
   'Pute',
  ];

export default p;      