const r = [
   'Rabauke',
   'Rabe',
   'rabiat' ,
   'Radau, Radaubruder',
   'rammen'  ,
   'ramponiert' ,
   'Rangelei',
   'rascheln',
   'Ratsch'  ,
   'rattern' ,  //rattern:              
   'Räuberpistole' ,
   'Rauflust',  //Rauflust:
   'Raunen, raunen' ,
   'Raureif' , 
   'recken',
   'Reinfall',
   'reinsemmeln'  ,
   'reißen (sich um etwas)' ,
   'reißerisch' ,
   'Rempler',
   'renitent' ,
   'requirieren' ,
   'reüssieren',
   'Revers',
   'Riegel'  ,
   'rieseln',
   'Rinde',
   'Rindvieh' ,
   'Rinnsal' ,
   'Ritze'  ,
   'robben' ,
   'röcheln', //röcheln:
   'roden' ,
   'rosten' ,
   'Rottenführer',  //Rottenführer:
   'rührig',
   'Rummel',
   'rumpeln',
   'rümpfen',
   'rumsen',
   'rupfen',
   ];

export default r;      
