const s = [
   'säumen', 
   'sausen' ,  
   'Schaben'  ,     
   'schade (zu schade sein)'  ,     
   'schälen' ,     
   'Schar'  ,     
   'schassen' ,     
   'schaufeln'  ,    
   'schaukeln'  ,     
   'scheiteln' ,
   'scheppern' ,
   'Scherbe' ,
   'scheren'  ,
   'scheuern'  ,
   'schielen'  ,
   'schikanieren'  ,
   'Schimmel' ,
   'Schimmer (keinen blassen...)',
   'schimmern'  ,
   'Schinder, schinden' ,
   'Schlamassel',
   'Schlauch' ,
   'schleifen' ,
   'schlendern'  ,
   'Schliere, schlieren'  ,
   'schluchzen'  ,
   'Schlüpfer',
   'schlüpfrig'  ,
   'schmettern' ,
   'schmiegen (sich)' ,
   'Schmiere stehen',
   'Schmiererei, schmieren'  ,
   'Schmierfink'  ,
   'Schminke' ,
   'schmoren'  ,
   'Schmuck, schmuck' ,
   'Schmunzeln, schmunzeln'  ,
   'Schmutzfink',
   'Schnalle, schnallen'  ,
   'Schnapsidee' ,
   'schnarchen' ,
   'schnattern'  ,
   'schneidig'  , 
   'schnieke',
   'schnippisch'  ,
   'schnörkelig'  ,
   'schnorren, anschnorren' ,
   'Schnösel'  ,
   'schnuppern'  ,
   'Schnur'  ,
   'schnurstracks' ,
   'Schotter' ,
   'Schrippe',
   'Schrott'  ,
   'Schrubber'  ,
   'schubsen' ,
   'schummrig',
   'Schund'  ,
   'schunkeln' ,
   'Schürze' ,
   'Schüssel' ,
   'schütten' ,
   'schütter' ,
   'Schütze',
   'schwanen'  ,
   'Schwanz einziehen/einkneifen',
   'Schwebebahn'  ,
   'Schwitzkasten' ,
   'Seil'  ,
   'sickern' ,
   'skandieren' ,
   'Sore',
   'soufflieren',
   'Spalier',
   'Spaten' ,
   'speckig' ,
   'sperrangelweit' ,
   'Sperrhaken' ,
   'spicken' ,
   'spitzkriegen',
   'Sprechmuschel'  ,
   'Spülbürste',
   'Spüle',
   'spuren' ,
   'sputen (sich)' ,
   'Stadtstreicher' ,
   'staksen'  ,
   'Standpauke' ,
   'Stange'  ,
   'Stapel, stapeln' ,
   'stapfen'  ,
   'starren (vor Schmutz starren)' ,
   'Statist' ,
   'Stativ'  ,
   'statuieren'  ,
   'Stecknadel im Heuhaufen'  ,
   'Steg' ,
   'stibitzen'  ,
   'Stich (einen Stich versetzen)',
   'Stiefel, stiefeln' ,
   'stieren' ,
   'Strebe'  ,
   'Streich spielen',
   'Strippe'  ,
   'stromern' ,
   'strunzdämlich'  ,
   'Stulle',
   'süffisant',
   'Sündenpfuhl',
   ];

export default s;      
