const s = [
   'Sägemehl',
   'säumen', 
   'sausen' ,  
   'Schaben'  ,     
   'schade (zu schade sein)'  ,     
   'schälen' ,     
   'Schar'  , 
   'Scharfmacher' ,   
   'schassen' ,     
   'schaufeln, Schaufel'  ,    
   'schaukeln'  ,     
   'scheiteln, Scheitel',
   'Scheiterhaufen',
   'schellen',
   'scheppern' ,
   'Scherbe' ,
   'scheren (sich)'  ,
   'scheuern'  ,
   'schielen'  ,
   'schikanieren'  ,
   'Schilde (etwas im S. führen)',
   'Schimmel, (ver)schimmeln',
   'Schimmer (keinen blassen S.)',
   'schimmern'  ,
   'Schinder, schinden' ,
   'Schlamassel',
   'Schlauberger',
   'Schlauch' ,
   'schleifen' ,
   'schlendern'  ,
   'Schleuse',
   'Schliere, schlieren'  ,
   'schliddern, schlittern',
   'schluchzen'  ,
   'Schlüpfer',
   'schlüpfrig'  ,
   'schmettern' ,
   'schmiegen (sich)' ,
   'Schmiere stehen',
   'Schmiererei, schmieren, schmierig'  ,
   'Schmierfink'  ,
   'Schminke' ,
   'schmissig',
   'Schmonzette',
   'schmoren'  ,
   'Schmuck, schmuck' ,
   'Schmuddel, Schmuddelwetter',
   'Schmunzeln, schmunzeln'  ,
   'Schmutzfink',
   'Schnalle, schnallen'  ,
   'Schnapsidee' ,
   'schnarchen' ,
   'schnattern'  ,
   'schneidig'  , 
   'schnieke',
   'schnippen',
   'schnippisch'  ,  
   'schnörkelig'  ,
   'schnorren, anschnorren' ,
   'Schnösel'  ,
   'schnuppern'  ,
   'Schnur'  ,
   'schnurstracks' ,
   'schnurz­pie­pe, schnurzegal',
   'Schotter' ,
   'schrammen',
   'schrappen',
   'Schraubstock',
   'Schrippe',
   'Schritt',
   'Schrott'  ,
   'Schrubber'  ,
   'schubsen' ,
   'schummrig',
   'Schund'  ,
   'schunkeln' ,
   'schüren',            
   'Schürze' ,
   'Schüssel' ,
   'schütten' ,          
   'schütter' ,
   'Schütze',
   'schwanen'  ,
   'Schwanz einziehen/einkneifen',
   'Schwebebahn'  ,
   'schwelgen',
   'Schwitzkasten' ,
   'schwülstig',
   'Seil'  ,
   'Sichtblende',
   'sickern' ,
   'Sippenhaft',
   'skandieren' ,
   'Sore',
   'soufflieren',
   'Spalier',
   'Spanner',
   'Spaten' ,
   'speckig' ,
   'sperrangelweit' ,
   'Sperrhaken' ,       
   'spicken' ,
   'Spieß, spießen',
   'spitzkriegen',
   'Sprechmuschel'  ,
   'Spreu vom Weizen trennen',
   'Spülbürste',
   'Spüle, spülen',
   'spuren' ,
   'sputen (sich)' ,
   'Stadtstreicher' ,
   'staksen'  ,
   'Standpauke' ,
   'Stange'  ,
   'Stapel, stapeln' ,
   'stapfen'  ,
   'starren (vor Schmutz starren)' ,
   'Statist' ,
   'Stativ'  ,
   'statuieren'  ,
   'Steckbrief',
   'Stecknadel im Heuhaufen'  ,
   'Steg' ,
   'stibitzen'  ,
   'Stich (einen Stich versetzen)',
   'Stiefel, stiefeln' ,
   'stieren' ,
   'stöbern',
   'stöckeln, Stöckelschuh',
   'stopfen, Stopfen',
   'stolzieren',
   'strampeln',
   'Strebe'  ,
   'Streich spielen',
   'Strickjacke',
   'Strippe'  ,
   'stromern' ,
   'Strudel',
   'strunzdämlich'  ,
   'Stulle',
   'stümperhaft',
   'süffisant',
   'summen',
   'Sündenpfuhl',
   ];

export default s;      
