const t = [
   'tapsen' ,
   'tätscheln',
   'taxieren' ,
   'Teufel tun' ,
   'Theke',
   'toben' ,
   'tollen',
   'tönen',
   'Tonne',         
   'torkeln',
   'Tracht Prügel',
   'Trasse' ,
   'Tresen' ,
   //'ins Kreuz treten  Tritt ins Kreuz'  ;   Nworte++;    Märzgefallene   111    German definition not found; entry in worte_T.js started, not finished
   'triezen' ,
   'trippeln',  
   'trollen (sich)' ,  
   'Tropf' ,  
   'Tropfen' , 
   'Tross/Troß' , 
   'Trost (nicht ganz bei Trost sein)' ,  
   'Trott, trotten' ,
   'Trottel' ,
   'Trubel' ,
   'Truhe' ,
   'tuckern',
   'tünchen, Tünche',
   'tunken',
   'tupfen' ,   
   'türken',
   'tuscheln' , 
];

export default t;      

