const v = [
   'Verband' ,
   'verbeulen',
   'verbocken'  ,
   'Verdeck',
   'verdenken' ,
   'verdonnern' ,
   'verdünnisieren (sich)' ,
   'verfilzen'  ,
   'vergaloppieren (sich)',
   'vergewissern (sich)'  ,
   'verhageln' ,
   'verhallen' ,
   'verheddern (sich)',
   'verhexen'  ,
   'verhunzen',
   'verkatert, Kater',   
   'verkneifen (sich)' ,
   'verknicken' ,
   'verkommen',
   'verkrümeln'  ,
   'verminen'  ,
   'verpetzen'  ,
   'verplempern' ,
   'verrecken' ,
   'verrenken (sich)',
   'verrennen (sich)' ,
   'verrucht' ,
   'verrufen, Verrufenheit',
   'verrußt' ,
   'verrutschen' ,
   'verschanzen (sich)' ,
   'verschimmeln' ,
   'Verschlag' ,
   'verschmieren' ,
   'verschnupft' ,
   'verschnüren',
   'verschollen' ,
   'verschorft' ,
   'verschrumpeln' ,
   'verschütten' ,
   'versehen' ,
   'versehentlich' ,
   'versengen' ,
   //worte[Nworte] = 'versehrt'  ;   Nworte++;   fix this in worte_V.js
   'versickern',
   'verstauen' ,
   'Verstellung' ,
   'verstockt'  ,
   'vertrackt' ,
   'verunglimpfen',
   'verunzieren' ,
   'Verwahrlosung' ,
   'verwaisen'  ,
   'verwegen' ,
   'verwesen' ,
   'verwetten' ,
   'verwüsten' ,
   'vierschrötig' ,
   'vögeln',
   'vorgaukeln' ,
   'vorsintflutlich',
];

export default v;    