const v = [
   'Ventil',
   'Verband' ,
   'verbeulen',
   'verbocken'  ,
   'Verdeck',
   'verdenken' ,
   'verdonnern' ,
   'verdruckst',
   'verdünnisieren (sich)' ,
   'verfilzen'  ,
  // 'verflixt',  open with more examples
   'vergackeiern',
   'vergaloppieren (sich)',
   'vergewissern (sich)'  ,
   'ver­grau­len, Vergraulung',
   'verhageln' ,
   'verhallen' ,
   'verheddern (sich)',
   'verhexen'  ,
   'verhunzen',
   'verkatert, Kater',   
   'verkneifen (sich)' ,
   'verknicken' ,
   'verknoten',
   'verkommen',
   'verkorkst, verkorken',
   'verkriechen (sich)',
   'verkrümeln'  ,
   'vermasseln',
   'verminen'  ,
   'verpetzen'  ,
   'verpfeifen',
   'verplappern (sich)',
   'verplempern' ,
   'verrammeln',
   'verrecken' ,
   'verrenken (sich)',
   'verrennen (sich)' ,
   'verrucht' ,
   'verrufen, Verrufenheit',
   'verrußt' ,
   'verrutschen' ,
   'versauen',
   'verschanzen (sich)' ,
   'verscherzen',
   'verschieben',
   'verschimmeln' ,
   'Verschlag' ,
   'verschmieren' ,
   'verschnupft' ,
   'verschnüren',
   'verschollen' ,
   'verschorft' ,
   'verschrumpeln' ,
   'verschütten' ,
   'versehen' ,
   'versehentlich' ,
//   'versehren',   need more past examples
   'versengen' ,
   'versickern',
   'versiegen',
   'verstauen' ,
   'Verstellung' ,
   'verstockt'  ,
   'vertrackt' ,
   'vertreten (sich)',
   'vertun, vertan',
   'verunglimpfen',
   'verunzieren' ,
   'Verwahrlosung' ,
   'verwaisen'  ,
   'verwegen' ,
   'verwesen' ,
   'verwetten' ,
   'verwittern, Verwitterung',
   'verwüsten' ,
   'vierschrötig' ,
   'vögeln',
   'vorgaukeln' ,
   'Vorhängeschloss',
   'vorsintflutlich',
];

export default v;    