const w = [
   'Wade' ,
   'wähnen',
   'Wappen' ,
   'Wassern (mit allen W. gewaschen)',
   'wedeln' ,
   'wegducken (sich)' ,
   'Wehwehchen',
   'weichklopfen' ,
   'Weihrauch, Weihrauchschwenker',
   'wellen (sich), Welle',
   'Wickelgamasche' ,
   'wie aus einem Ei gepellt',
   'wie bestellt und nicht abgeholt',
   'wienern' ,
   'wimmern' ,
   'winden' ,
   'Wink mit dem Zaunpfahl' ,
   'Winkel' ,
   'Winkeladvokat',
   'Wipfel',
   'wippen' ,
   'Witzbold',
   'wogen' ,
   'Wohl bekomm\'s!',
   'Wohlgefallen (sich in W. auflösen)',
   'wölben',
   'wühlen' ,
   'wummern, Gewummer',
   'wuscheln',
   'wuseln',
   'wüten',
   ];

export default w;      