const z = [
   'zackig' ,
   'Zapfen',
   'zappeln',
   'Zarge' ,
   'zechen',
   'Zehenspitze' ,
   'Zeltplane' ,
   'zerdeppern',
   'zerfleddert' ,
   'zerknicken' ,
   'zerknirscht',
   'zerknittern',
   'zerknüllen' ,
   'zerren' ,
   'zerschunden' ,
   'zerwühlen' ,
   'zerzausen' ,
   'Zeug (was das Zeug hält)',
   'Zicke, Zicken machen'  ,
   'Ziegelwand'  ,
   'zig' ,
   'Zinken' ,
   'Zinnober',
   'zischen' ,     
   'zittern' ,
   'zittrig' ,
   'zockeln' ,
   'Zopf'  ,
   'Zucht' ,
   'züchtigen',
   'zücken' ,       
   'Zugehfrau' ,
   'zügeln' ,
   'zünftig' ,
   'zupasskommen' ,
   'zurren, festzurren',
   'zupfen',
   'Zuspruch' ,
   'zwinkern' , 
   'zwirbeln', 
   'Zwirn',
];

export default z;         
