const z = [
   'zackig' ,    
   'zahm, handzahm',
   'Zange (in die Z. nehmen)',
   'zanken (sich)',
   'Zapfen',
   'zappeln',
   'Zarge' ,
   'zaudern',
   'Zaunpfahlwink',
   'zechen',
   'Zehenspitze' ,
   'Zeltplane' ,
   'zerdeppern',
   'zerfleddert' ,
   'zerknicken' ,
   'zerknirscht',
   'zerknittern',
   'zerknüllen' ,
   'zermatschen',
   'zerpflücken',
   'zerren' ,
   'zerschunden' ,
   'zerwühlen' ,
   'zerzausen' ,
   'Zeug (was das Z. hält)',
   'Zicke, Zicken machen'  ,
   'Ziegelwand'  ,
   'zig' ,
   'Zinken' ,
   'Zinnober', 
   'Zipperlein'   ,
   'zischen' ,     
   'zittern' ,
   'zittrig' ,
   'zockeln' ,
   'Zopf'  ,
   'zu nahe treten',
   'Zucht' ,
   'züchtigen',
   'zücken' ,       
   'Zugehfrau' ,
   'zügeln' ,
   'zünftig' ,
   'zupasskommen' ,
   'zupfen',
   'zuprosten',
   'zurren, festzurren',
   'Zuspruch' ,
   'zuwanken',
   'Zwang (sich keinen Z. antun)',
   'zwinkern' , 
   'zwirbeln', 
   'Zwirn',
   'zwitschern',
];

export default z;         
